### ISSUE TITLE
Session breaks upon parsing context

### ISSUE THREAD

**Issue by binarynoise** [fmaclen/hollama#103]
> Sorry, something went wrong.
> ```
> SyntaxError: JSON.parse: end of data when ',' or ']' was expected at line 1 column x of the JSON data
> ```

This is independent from the knowledge as system prompt experiment.

Here is the network traffic for that session as [har file](http://www.softwareishard.com/blog/har-12-spec/): [localhost_Archive [24-07-20 17-45-41].har.json](https://github.com/user-attachments/files/16321571/localhost_Archive.24-07-20.17-45-41.har.json). You can load it into Firefox or Chrome to see the details.

As far as I can tell, ollama does send a valid response (in contrast to #97) but hollama for some reason fails to parse the last line with the context. The x varies wildly ~~around 30k~~.
It happens around the 5th or 6th response for me with different models and prompts.

As a consequence, the conversation's context is lost and a new conversation begins on retrying the last message. Sometimes not everything gets lost but the conversation is broken anyway.

As a workaround, would it be possible to hold onto the last valid context and use that when retrying the message?

Switching to another conversation and coming back to retry does actually trigger #97.

**Comment by binarynoise** [comment]
Or just save the returned context for each message to be able to start over at a given point when the model starts generating nonsense

**Comment by fmaclen** [comment]
Thanks, I was able to replicate the issue.

I'm not entirely sure yet but I suspect is because we are trying to format the completion in "small chunks" as Ollama streams them, one of the chunks is causing a parser to break.

> As a workaround, would it be possible to hold onto the last valid context and use that when retrying the message?

Yeah, I wanted to implement something like this so messages can be retried or even edited. #9

**Comment by fmaclen** [comment]
Here's what I think it's happening, when we catch an error during a completion (any kind of error) the prompt is reset so the user can try again, but when it re-submits the prompt the context array with all of the tokens is lost.

**Comment by fmaclen** [comment]
I don't think we can predict when the JSON parsing will fail, but whenever there is any kind of error the UI should hint a clear path on how to fix it (if possible).

In a large number of cases I expect simply "retrying" should fix most issues: https://github.com/fmaclen/hollama/issues/9#issuecomment-2241328191

**Comment by binarynoise** [comment]
#9 doesn't help at all for this problem. Regenerating the failing message or even one earlier will cause the same error again.

**Comment by fmaclen** [comment]
@binarynoise true, #103 won't be fixed by #106.

What I meant is that in order to close this issue we want to make sure you can indeed click "Retry" to continue the session as if the error never happened.

**Comment by fmaclen** [comment]
I can now reliably get this error:
```
SyntaxError: JSON.parse: end of data when ',' or ']' was expected at line 1 column x of the JSON data
```

I think this is caused by exceeding the limit of the context window on the model, which causes the completion to get truncated. This is what I see in the Ollama logs when I retry the failed message.

```shell
[GIN] 2024/07/21 - 17:47:48 | 200 |  1.964507833s |             ::1 | POST     "/api/generate"
INFO [update_slots] input truncated | n_ctx=2048 n_erase=2767 n_keep=4 n_left=2044 n_shift=1022 tid="0x1f6960c00" timestamp=1721598478
```

In a session with `llama3:latest` I started seeing the error above with `15233` tokens in the context field.

**Comment by fmaclen** [comment]
I just added a hint about the cause of the error:

![localhost_5174_sessions_6fpqqn](https://github.com/user-attachments/assets/0e508d50-a88d-47ee-9dec-
5c8a04635e82)

A more final solution to this issue could be to switch to the `/api/chat` endpoint (instead of `/api/generate`) which probably fails more gracefully, but if this error is really only caused by the exceeding tokens in the context window we can probably do other things that would be more useful such as #54 and #7

**Comment by binarynoise** [comment]
The chat version works great – until you reference something from three pages ago.
I'm wondering if there isn't any way to for either variant to progressively condense the most important stuff into the context instead of keeping everything.

**Comment by fmaclen** [comment]
I'm not entirely sure what would be the best way to conserve the overall context as much as possible.

But the [recent updates to Ollama](https://github.com/ollama/ollama/releases/tag/v0.3.0) (tool and web scraping) are only available on the `/api/chat` endpoint so it's probably worth upgrading to it, close this issue and figure out how the context window issue separately.

@binarynoise Do you feel like you often exceed the context window limit in normal use? or only occasionally?
