### ISSUE TITLE
Persistent storage?

### ISSUE THREAD

**Issue by quaintdev** [fmaclen/hollama#161]
I restarted my computer and all the chats I had are lost. I am using docker command to run hollama. Any suggestions?

**Comment by fmaclen** [comment]
@quaintdev all of the data is stored in your browser's `localStorage`.

Where you by any chance using Hollama in an incognito/private window?
If so, the moment you close the window all the data gets wiped.

**Comment by quaintdev** [comment]
Oh ok. I had cleaned up the browser data and in that it probably got lost. 
Any plans to support permanent storage or to export the data stored in browser?

Thanks for creating hollama. I love it!

**Comment by fmaclen** [comment]
Unfortunately there are no immediate plans for supporting a more permanent storage solution.
This is primarily because the app was architected to be able to run entirely on the browser without any external dependencies

There's definitely a lot of potential we can unlock if the Docker or Desktop versions of the app have a more powerful database, but right now the focus is on getting the best UX possible with the constraints of a browser environment.

That being said I'd like to add an option to at least import/export sessions #126
