### ISSUE TITLE
Make LLM output area bigger? And reduce size of input text box

### ISSUE THREAD

**Issue by ishaanbhimwal** [fmaclen/hollama#200]
Is there a way to do this? I feel the output area is too small, and I have to scroll all the time. Maybe hide the sessions tab?

![image](https://github.com/user-attachments/assets/947c1eb2-a3fe-46b8-b570-8e43c6bcabb8)

Thank you!

**Comment by fmaclen** [comment]
Yes, this is something that's been bugging me as well.
I have some plans for reducing the elements around the prompt field a fair amount, perhaps even the header.

**Comment by fmaclen** [comment]
@ishaanbhimwal @wenrolland just made a few changes to increase the size of the messages area, can you try it out and let me know what you think and/or if you find any bugs?

https://200-increase-session-content.hollama.pages.dev/

Here's a list of changes made:

- Reduced the height of the session header
- Moved the _"fullscreen"_ text editor switch next to the existing toolbar
- Removed the "Available models" label from the model select field
- Reduced the height of the prompt `textarea` slightly
- On Chromium browsers the height of the `textarea` should grow automatically as new lines are added
- Other minor styling tweaks

> Maybe put a smaller Run button next to the input windows to gain 2 more lines

I don't want to move the Run button just yet because we are planning on adding a [new toolbar for uploading images/docs](https://github.com/fmaclen/hollama/issues/116#issuecomment-2251424660) that will likely be located next to it.

**Comment by ishaanbhimwal** [comment]
Thanks for the changes! I think it already looks better than the previous UI. Maybe the first box can be removed? (see from the screenshot below) and the we can add a toggle to show/hide the choose model field. Just add a small "Run" button there as seen [here](https://github.com/fmaclen/hollama/issues/116#issuecomment-2251424660).

![image](https://github.com/user-attachments/assets/ecbf2f2b-4dd4-496a-9691-f106a30a08f0)

**Comment by fmaclen** [comment]
I'm curious, what screen resolution are you using? That looks like a very narrow aspect ratio.

> Maybe the first box can be removed?

Unfortunately I can't remove the box at the top, we need that toolbar because we are planning on [allowing custom](https://github.com/fmaclen/hollama/issues/164)/[AI-generated session titles](https://github.com/fmaclen/hollama/issues/168), plus is the only way we currently have for copying the entire session.

As far as the other suggestions I'm not particularly opposed to them either, but toggling existing elements or moving the Run button are not trivial implementations so they won't be addressed at this time. We'll probably tweak things over time but my suggestion (beyond these changes) would be to _zoom out_ the UI (`Ctrl/Cmd -`).

**Comment by fmaclen** [comment]
Closed by #206
