### ISSUE TITLE
Support `llama.cpp` directly, bypassing `ollama`

### ISSUE THREAD

**Issue by savchenko** [fmaclen/hollama#233]
Given the close relationship between ollama and [llama.cpp](https://github.com/ggerganov/llama.cpp), would it be possible to support [llama-server](https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#web-server)? 

It exposes [OpenAI-compatible](https://github.com/openai/openai-openapi) HTTP endpoint on localhost.

**Comment by fmaclen** [comment]
We recently added support for OpenAI servers, you can find the configuration in the [Settings](https://hollama.fernando.is/settings) view.

Can you configure it with your llama-server and let me know if it works?

**Comment by fmaclen** [comment]
Thanks for the detailed report, I'll need to take a closer look to see where it might be going wrong.

> I have noticed that OpenAPI endpoint can't be saved without an API key

Yeah, since this feature was designed specifically for OpenAI it wouldn't work without an API key so that's why we made it "mandatory", but we should probably document this better.

**Comment by fmaclen** [comment]
Found the cause of the problem. Our current implementation filters out any models that don't include `gpt` in their name.
Therefore `Qwen2.5-Coder-32B-Instruct-Q4_K_S.gguf` gets filtered out.

Removing the filter makes it work:

![image](https://github.com/user-attachments/assets/bdd37c98-eb12-43df-ba39-9a49e2e44064)

This is because when we get the models from OpenAI it also sends back a list of non-LLM models that are incompatible with Hollama.

**Comment by fmaclen** [comment]
@savchenko here's a work-in-progress demo if you want to check it out:
https://llama-cpp-llama-server-opena.hollama.pages.dev/settings

You'll need to add a **"OpenAI compatible"** connection type to setup your llama.cpp server.

**Comment by fmaclen** [comment]
@savchenko _slightly broken_ is quite the understatement 😅 
Just pushed a fix, if you refresh the page it should look correct in Firefox.

**Comment by fmaclen** [comment]
Thanks for the update.

I was able to replicate the issue you are seeing with Firefox and I'm pretty sure it's caused by some [_hacky_ code](https://github.com/fmaclen/hollama/pull/234/files#diff-8ce18b89a66ab14e41828e18ffda5871f90e6f45ebb78341e85802114c06bd2cR83-R86) I wrote just to quickly try things out.

That being said, it _works fine_ for me in Chromium. If you were using the most recent release of Hollama in the same browser (with the same URL/hostname) it's possible it might have conflicting settings stored in `localStorage`. This is something I still need to test/QA before releasing this new version.

Couple of questions, if you don't mind:

1. What command are you running to build the container?
2. Does the UI load correctly in Firefox from the live demo? https://llama-cpp-llama-server-opena.hollama.pages.dev/settings
3. In Chromium, do you still get the same error `Invalid strategy` in an Incognito window?

**Comment by fmaclen** [comment]
@savchenko thanks for the clarification.

Try to build [`fee51b7`](https://github.com/fmaclen/hollama/commit/fee51b71e8d78c5ef25f22549e9ae692450fc8d8) which should have fixed the `Invalid strategy` error and the layout issues in Firefox.
There are still a handful of smaller bugs but you should be able to interact with `llama-sever` 🤞

**Comment by fmaclen** [comment]
Glad to hear it's working!

> Shall this be closed?

No, the issue will be closed automatically once the feature is released.
There is still a fair amount of cleanup and testing I need to do before we can push this out.
